FROM node:22-alpine
RUN corepack enable
WORKDIR /app

COPY . .
RUN pnpm install --frozen-lockfile

EXPOSE 4000
CMD ["sh", "-c", "pnpm --filter @odfinex/db db:migrate && pnpm --filter @odfinex/api start"]
